// Decompiled with JetBrains decompiler
// Type: Terraria.Initializers.AchievementInitializer
// Assembly: Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null
// MVID: E90A5A2F-CD10-4A2C-9D2A-6B036D4E8877
// Assembly location: E:\Decompile\Terraria\Terraria.exe

using Terraria.Achievements;
using Terraria.GameContent.Achievements;
using Terraria.GameContent.UI.Chat;
using Terraria.Localization;

namespace Terraria.Initializers
{
    public class AchievementInitializer
    {
        public static void Load()
        {
            if (Main.netMode == 2)
                return;
            var achievement1 = new Achievement("TIMBER");
            achievement1.AddCondition(ItemPickupCondition.Create((short) 9, (short) 619, (short) 2504, (short) 620,
                (short) 2503, (short) 2260, (short) 621, (short) 911, (short) 1729));
            Main.Achievements.Register(achievement1);
            var achievement2 = new Achievement("NO_HOBO");
            achievement2.AddCondition((AchievementCondition) ProgressionEventCondition.Create(8));
            Main.Achievements.Register(achievement2);
            var achievement3 = new Achievement("OBTAIN_HAMMER");
            achievement3.AddCondition(ItemPickupCondition.Create((short) 2775, (short) 2746, (short) 3505, (short) 654,
                (short) 3517, (short) 7, (short) 3493, (short) 2780, (short) 1513, (short) 2516, (short) 660,
                (short) 3481, (short) 657, (short) 922, (short) 3511, (short) 2785, (short) 3499, (short) 3487,
                (short) 196, (short) 367, (short) 104, (short) 797, (short) 2320, (short) 787, (short) 1234,
                (short) 1262, (short) 3465, (short) 204, (short) 217, (short) 1507, (short) 3524, (short) 3522,
                (short) 3525, (short) 3523, (short) 1305));
            Main.Achievements.Register(achievement3);
            var achievement4 = new Achievement("OOO_SHINY");
            achievement4.AddCondition(TileDestroyedCondition.Create((ushort) 7, (ushort) 6, (ushort) 9, (ushort) 8,
                (ushort) 166, (ushort) 167, (ushort) 168, (ushort) 169, (ushort) 22, (ushort) 204, (ushort) 58,
                (ushort) 107, (ushort) 108, (ushort) 111, (ushort) 221, (ushort) 222, (ushort) 223, (ushort) 211));
            Main.Achievements.Register(achievement4);
            var achievement5 = new Achievement("HEART_BREAKER");
            achievement5.AddCondition(TileDestroyedCondition.Create((ushort) 12));
            Main.Achievements.Register(achievement5);
            var achievement6 = new Achievement("HEAVY_METAL");
            achievement6.AddCondition(ItemPickupCondition.Create((short) 35, (short) 716));
            Main.Achievements.Register(achievement6);
            var achievement7 = new Achievement("I_AM_LOOT");
            achievement7.AddCondition(CustomFlagCondition.Create("Peek"));
            Main.Achievements.Register(achievement7);
            var achievement8 = new Achievement("STAR_POWER");
            achievement8.AddCondition(CustomFlagCondition.Create("Use"));
            Main.Achievements.Register(achievement8);
            var achievement9 = new Achievement("HOLD_ON_TIGHT");
            achievement9.AddCondition(CustomFlagCondition.Create("Equip"));
            Main.Achievements.Register(achievement9);
            var achievement10 = new Achievement("EYE_ON_YOU");
            achievement10.AddCondition(NPCKilledCondition.Create((short) 4));
            Main.Achievements.Register(achievement10);
            var achievement11 = new Achievement("SMASHING_POPPET");
            achievement11.AddCondition((AchievementCondition) ProgressionEventCondition.Create(7));
            Main.Achievements.Register(achievement11);
            var achievement12 = new Achievement("WORM_FODDER");
            achievement12.AddCondition(NPCKilledCondition.Create((short) 13, (short) 14, (short) 15));
            Main.Achievements.Register(achievement12);
            var achievement13 = new Achievement("MASTERMIND");
            achievement13.AddCondition(NPCKilledCondition.Create((short) 266));
            Main.Achievements.Register(achievement13);
            var achievement14 = new Achievement("WHERES_MY_HONEY");
            achievement14.AddCondition(CustomFlagCondition.Create("Reach"));
            Main.Achievements.Register(achievement14);
            var achievement15 = new Achievement("STING_OPERATION");
            achievement15.AddCondition(NPCKilledCondition.Create((short) 222));
            Main.Achievements.Register(achievement15);
            var achievement16 = new Achievement("BONED");
            achievement16.AddCondition(NPCKilledCondition.Create((short) 35));
            Main.Achievements.Register(achievement16);
            var achievement17 = new Achievement("DUNGEON_HEIST");
            achievement17.AddCondition(ItemPickupCondition.Create((short) 327));
            achievement17.AddCondition((AchievementCondition) ProgressionEventCondition.Create(19));
            Main.Achievements.Register(achievement17);
            var achievement18 = new Achievement("ITS_GETTING_HOT_IN_HERE");
            achievement18.AddCondition(CustomFlagCondition.Create("Reach"));
            Main.Achievements.Register(achievement18);
            var achievement19 = new Achievement("MINER_FOR_FIRE");
            achievement19.AddCondition(ItemCraftCondition.Create((short) 122));
            Main.Achievements.Register(achievement19);
            var achievement20 = new Achievement("STILL_HUNGRY");
            achievement20.AddCondition(NPCKilledCondition.Create((short) 113, (short) 114));
            Main.Achievements.Register(achievement20);
            var achievement21 = new Achievement("ITS_HARD");
            achievement21.AddCondition((AchievementCondition) ProgressionEventCondition.Create(9));
            Main.Achievements.Register(achievement21);
            var achievement22 = new Achievement("BEGONE_EVIL");
            achievement22.AddCondition((AchievementCondition) ProgressionEventCondition.Create(6));
            Main.Achievements.Register(achievement22);
            var achievement23 = new Achievement("EXTRA_SHINY");
            achievement23.AddCondition(TileDestroyedCondition.Create((ushort) 107, (ushort) 108, (ushort) 111,
                (ushort) 221, (ushort) 222, (ushort) 223));
            Main.Achievements.Register(achievement23);
            var achievement24 = new Achievement("HEAD_IN_THE_CLOUDS");
            achievement24.AddCondition(CustomFlagCondition.Create("Equip"));
            Main.Achievements.Register(achievement24);
            var achievement25 = new Achievement("LIKE_A_BOSS");
            achievement25.AddCondition(ItemPickupCondition.Create((short) 1133, (short) 1331, (short) 1307, (short) 267,
                (short) 1293, (short) 557, (short) 544, (short) 556, (short) 560, (short) 43, (short) 70));
            Main.Achievements.Register(achievement25);
            var achievement26 = new Achievement("BUCKETS_OF_BOLTS");
            achievement26.AddCondition(NPCKilledCondition.Create((short) 125, (short) 126));
            achievement26.AddConditions(NPCKilledCondition.CreateMany((short) sbyte.MaxValue, (short) 134));
            achievement26.UseConditionsCompletedTracker();
            Main.Achievements.Register(achievement26);
            var achievement27 = new Achievement("DRAX_ATTAX");
            achievement27.AddCondition(ItemCraftCondition.Create((short) 579, (short) 990));
            Main.Achievements.Register(achievement27);
            var achievement28 = new Achievement("PHOTOSYNTHESIS");
            achievement28.AddCondition(TileDestroyedCondition.Create((ushort) 211));
            Main.Achievements.Register(achievement28);
            var achievement29 = new Achievement("GET_A_LIFE");
            achievement29.AddCondition(CustomFlagCondition.Create("Use"));
            Main.Achievements.Register(achievement29);
            var achievement30 = new Achievement("THE_GREAT_SOUTHERN_PLANTKILL");
            achievement30.AddCondition(NPCKilledCondition.Create((short) 262));
            Main.Achievements.Register(achievement30);
            var achievement31 = new Achievement("TEMPLE_RAIDER");
            achievement31.AddCondition(TileDestroyedCondition.Create((ushort) 226));
            Main.Achievements.Register(achievement31);
            var achievement32 = new Achievement("LIHZAHRDIAN_IDOL");
            achievement32.AddCondition(NPCKilledCondition.Create((short) 245));
            Main.Achievements.Register(achievement32);
            var achievement33 = new Achievement("ROBBING_THE_GRAVE");
            achievement33.AddCondition(ItemPickupCondition.Create((short) 1513, (short) 938, (short) 963, (short) 977,
                (short) 1300, (short) 1254, (short) 1514, (short) 679, (short) 759, (short) 1446, (short) 1445,
                (short) 1444, (short) 1183, (short) 1266, (short) 671));
            Main.Achievements.Register(achievement33);
            var achievement34 = new Achievement("BIG_BOOTY");
            achievement34.AddCondition((AchievementCondition) ProgressionEventCondition.Create(20));
            Main.Achievements.Register(achievement34);
            var achievement35 = new Achievement("FISH_OUT_OF_WATER");
            achievement35.AddCondition(NPCKilledCondition.Create((short) 370));
            Main.Achievements.Register(achievement35);
            var achievement36 = new Achievement("OBSESSIVE_DEVOTION");
            achievement36.AddCondition(NPCKilledCondition.Create((short) 439));
            Main.Achievements.Register(achievement36);
            var achievement37 = new Achievement("STAR_DESTROYER");
            achievement37.AddConditions(NPCKilledCondition.CreateMany((short) 517, (short) 422, (short) 507,
                (short) 493));
            Main.Achievements.Register(achievement37);
            var achievement38 = new Achievement("CHAMPION_OF_TERRARIA");
            achievement38.AddCondition(NPCKilledCondition.Create((short) 398));
            Main.Achievements.Register(achievement38);
            var achievement39 = new Achievement("BLOODBATH");
            achievement39.AddCondition((AchievementCondition) ProgressionEventCondition.Create(5));
            Main.Achievements.Register(achievement39);
            var achievement40 = new Achievement("SLIPPERY_SHINOBI");
            achievement40.AddCondition(NPCKilledCondition.Create((short) 50));
            Main.Achievements.Register(achievement40);
            var achievement41 = new Achievement("GOBLIN_PUNTER");
            achievement41.AddCondition((AchievementCondition) ProgressionEventCondition.Create(10));
            Main.Achievements.Register(achievement41);
            var achievement42 = new Achievement("WALK_THE_PLANK");
            achievement42.AddCondition((AchievementCondition) ProgressionEventCondition.Create(11));
            Main.Achievements.Register(achievement42);
            var achievement43 = new Achievement("KILL_THE_SUN");
            achievement43.AddCondition((AchievementCondition) ProgressionEventCondition.Create(3));
            Main.Achievements.Register(achievement43);
            var achievement44 = new Achievement("DO_YOU_WANT_TO_SLAY_A_SNOWMAN");
            achievement44.AddCondition((AchievementCondition) ProgressionEventCondition.Create(12));
            Main.Achievements.Register(achievement44);
            var achievement45 = new Achievement("TIN_FOIL_HATTER");
            achievement45.AddCondition((AchievementCondition) ProgressionEventCondition.Create(13));
            Main.Achievements.Register(achievement45);
            var achievement46 = new Achievement("BALEFUL_HARVEST");
            achievement46.AddCondition((AchievementCondition) ProgressionEventCondition.Create(15));
            Main.Achievements.Register(achievement46);
            var achievement47 = new Achievement("ICE_SCREAM");
            achievement47.AddCondition((AchievementCondition) ProgressionEventCondition.Create(14));
            Main.Achievements.Register(achievement47);
            var achievement48 = new Achievement("STICKY_SITUATION");
            achievement48.AddCondition((AchievementCondition) ProgressionEventCondition.Create(16));
            Main.Achievements.Register(achievement48);
            var achievement49 = new Achievement("REAL_ESTATE_AGENT");
            achievement49.AddCondition((AchievementCondition) ProgressionEventCondition.Create(17));
            Main.Achievements.Register(achievement49);
            var achievement50 = new Achievement("NOT_THE_BEES");
            achievement50.AddCondition(CustomFlagCondition.Create("Use"));
            Main.Achievements.Register(achievement50);
            var achievement51 = new Achievement("JEEPERS_CREEPERS");
            achievement51.AddCondition(CustomFlagCondition.Create("Reach"));
            Main.Achievements.Register(achievement51);
            var achievement52 = new Achievement("FUNKYTOWN");
            achievement52.AddCondition(CustomFlagCondition.Create("Reach"));
            Main.Achievements.Register(achievement52);
            var achievement53 = new Achievement("INTO_ORBIT");
            achievement53.AddCondition(CustomFlagCondition.Create("Reach"));
            Main.Achievements.Register(achievement53);
            var achievement54 = new Achievement("ROCK_BOTTOM");
            achievement54.AddCondition(CustomFlagCondition.Create("Reach"));
            Main.Achievements.Register(achievement54);
            var achievement55 = new Achievement("MECHA_MAYHEM");
            achievement55.AddCondition((AchievementCondition) ProgressionEventCondition.Create(21));
            Main.Achievements.Register(achievement55);
            var achievement56 = new Achievement("GELATIN_WORLD_TOUR");
            achievement56.AddConditions(NPCKilledCondition.CreateMany((short) -5, (short) -6, (short) 1, (short) 81,
                (short) 71, (short) -3, (short) 147, (short) 138, (short) -10, (short) 50, (short) 59, (short) 16,
                (short) -7, (short) 244, (short) -8, (short) -1, (short) -2, (short) 184, (short) 204, (short) 225,
                (short) -9, (short) 141, (short) 183, (short) -4));
            achievement56.UseConditionsCompletedTracker();
            Main.Achievements.Register(achievement56);
            var achievement57 = new Achievement("FASHION_STATEMENT");
            achievement57.AddCondition(CustomFlagCondition.Create("Equip"));
            Main.Achievements.Register(achievement57);
            var achievement58 = new Achievement("VEHICULAR_MANSLAUGHTER");
            achievement58.AddCondition(CustomFlagCondition.Create("Hit"));
            Main.Achievements.Register(achievement58);
            var achievement59 = new Achievement("BULLDOZER");
            achievement59.AddCondition(CustomIntCondition.Create("Pick", 10000));
            achievement59.UseTrackerFromCondition("Pick");
            Main.Achievements.Register(achievement59);
            var achievement60 = new Achievement("THERE_ARE_SOME_WHO_CALL_HIM");
            achievement60.AddCondition(NPCKilledCondition.Create((short) 45));
            Main.Achievements.Register(achievement60);
            var achievement61 = new Achievement("DECEIVER_OF_FOOLS");
            achievement61.AddCondition(NPCKilledCondition.Create((short) 196));
            Main.Achievements.Register(achievement61);
            var achievement62 = new Achievement("SWORD_OF_THE_HERO");
            achievement62.AddCondition(ItemPickupCondition.Create((short) 757));
            Main.Achievements.Register(achievement62);
            var achievement63 = new Achievement("LUCKY_BREAK");
            achievement63.AddCondition(CustomFlagCondition.Create("Hit"));
            Main.Achievements.Register(achievement63);
            var achievement64 = new Achievement("THROWING_LINES");
            achievement64.AddCondition(CustomFlagCondition.Create("Use"));
            Main.Achievements.Register(achievement64);
            var achievement65 = new Achievement("DYE_HARD");
            achievement65.AddCondition(CustomFlagCondition.Create("Equip"));
            Main.Achievements.Register(achievement65);
            var achievement66 = new Achievement("SICK_THROW");
            achievement66.AddCondition(ItemPickupCondition.Create((short) 3389));
            Main.Achievements.Register(achievement66);
            var achievement67 = new Achievement("FREQUENT_FLYER");
            achievement67.AddCondition(CustomFloatCondition.Create("Pay", 10000f));
            achievement67.UseTrackerFromCondition("Pay");
            Main.Achievements.Register(achievement67);
            var achievement68 = new Achievement("THE_CAVALRY");
            achievement68.AddCondition(CustomFlagCondition.Create("Equip"));
            Main.Achievements.Register(achievement68);
            var achievement69 = new Achievement("COMPLETELY_AWESOME");
            achievement69.AddCondition(ItemPickupCondition.Create((short) 98));
            Main.Achievements.Register(achievement69);
            var achievement70 = new Achievement("TIL_DEATH");
            achievement70.AddCondition(NPCKilledCondition.Create((short) 53));
            Main.Achievements.Register(achievement70);
            var achievement71 = new Achievement("ARCHAEOLOGIST");
            achievement71.AddCondition(NPCKilledCondition.Create((short) 52));
            Main.Achievements.Register(achievement71);
            var achievement72 = new Achievement("PRETTY_IN_PINK");
            achievement72.AddCondition(NPCKilledCondition.Create((short) -4));
            Main.Achievements.Register(achievement72);
            var achievement73 = new Achievement("RAINBOWS_AND_UNICORNS");
            achievement73.AddCondition(CustomFlagCondition.Create("Use"));
            Main.Achievements.Register(achievement73);
            var achievement74 = new Achievement("YOU_AND_WHAT_ARMY");
            achievement74.AddCondition(CustomFlagCondition.Create("Spawn"));
            Main.Achievements.Register(achievement74);
            var achievement75 = new Achievement("PRISMANCER");
            achievement75.AddCondition(ItemPickupCondition.Create((short) 495));
            Main.Achievements.Register(achievement75);
            var achievement76 = new Achievement("IT_CAN_TALK");
            achievement76.AddCondition((AchievementCondition) ProgressionEventCondition.Create(18));
            Main.Achievements.Register(achievement76);
            var achievement77 = new Achievement("WATCH_YOUR_STEP");
            achievement77.AddCondition(CustomFlagCondition.Create("Hit"));
            Main.Achievements.Register(achievement77);
            var achievement78 = new Achievement("MARATHON_MEDALIST");
            achievement78.AddCondition(CustomFloatCondition.Create("Move", 1106688f));
            achievement78.UseTrackerFromCondition("Move");
            Main.Achievements.Register(achievement78);
            var achievement79 = new Achievement("GLORIOUS_GOLDEN_POLE");
            achievement79.AddCondition(ItemPickupCondition.Create((short) 2294));
            Main.Achievements.Register(achievement79);
            var achievement80 = new Achievement("SERVANT_IN_TRAINING");
            achievement80.AddCondition(CustomFlagCondition.Create("Finish"));
            Main.Achievements.Register(achievement80);
            var achievement81 = new Achievement("GOOD_LITTLE_SLAVE");
            achievement81.AddCondition(CustomIntCondition.Create("Finish", 10));
            achievement81.UseTrackerFromCondition("Finish");
            Main.Achievements.Register(achievement81);
            var achievement82 = new Achievement("TROUT_MONKEY");
            achievement82.AddCondition(CustomIntCondition.Create("Finish", 25));
            achievement82.UseTrackerFromCondition("Finish");
            Main.Achievements.Register(achievement82);
            var achievement83 = new Achievement("FAST_AND_FISHIOUS");
            achievement83.AddCondition(CustomIntCondition.Create("Finish", 50));
            achievement83.UseTrackerFromCondition("Finish");
            Main.Achievements.Register(achievement83);
            var achievement84 = new Achievement("SUPREME_HELPER_MINION");
            achievement84.AddCondition(CustomIntCondition.Create("Finish", 200));
            achievement84.UseTrackerFromCondition("Finish");
            Main.Achievements.Register(achievement84);
            var achievement85 = new Achievement("TOPPED_OFF");
            achievement85.AddCondition(CustomFlagCondition.Create("Use"));
            Main.Achievements.Register(achievement85);
            var achievement86 = new Achievement("SLAYER_OF_WORLDS");
            achievement86.AddCondition(NPCKilledCondition.Create((short) 13, (short) 14, (short) 15));
            achievement86.AddCondition(NPCKilledCondition.Create((short) 113, (short) 114));
            achievement86.AddCondition(NPCKilledCondition.Create((short) 125, (short) 126));
            achievement86.AddConditions(NPCKilledCondition.CreateMany((short) 4, (short) 35, (short) 50, (short) 222,
                (short) 113, (short) 134, (short) sbyte.MaxValue, (short) 262, (short) 245, (short) 439, (short) 398,
                (short) 370));
            achievement86.UseConditionsCompletedTracker();
            Main.Achievements.Register(achievement86);
            var achievement87 = new Achievement("YOU_CAN_DO_IT");
            achievement87.AddCondition((AchievementCondition) ProgressionEventCondition.Create(1));
            Main.Achievements.Register(achievement87);
            var achievement88 = new Achievement("MATCHING_ATTIRE");
            achievement88.AddCondition(CustomFlagCondition.Create("Equip"));
            Main.Achievements.Register(achievement88);
            var num1 = 0;
            var achievements1 = Main.Achievements;
            var achievementName1 = "TIMBER";
            var iconIndex1 = num1;
            var num2 = iconIndex1 + 1;
            achievements1.RegisterIconIndex(achievementName1, iconIndex1);
            var achievements2 = Main.Achievements;
            var achievementName2 = "NO_HOBO";
            var iconIndex2 = num2;
            var num3 = iconIndex2 + 1;
            achievements2.RegisterIconIndex(achievementName2, iconIndex2);
            var achievements3 = Main.Achievements;
            var achievementName3 = "OBTAIN_HAMMER";
            var iconIndex3 = num3;
            var num4 = iconIndex3 + 1;
            achievements3.RegisterIconIndex(achievementName3, iconIndex3);
            var achievements4 = Main.Achievements;
            var achievementName4 = "HEART_BREAKER";
            var iconIndex4 = num4;
            var num5 = iconIndex4 + 1;
            achievements4.RegisterIconIndex(achievementName4, iconIndex4);
            var achievements5 = Main.Achievements;
            var achievementName5 = "OOO_SHINY";
            var iconIndex5 = num5;
            var num6 = iconIndex5 + 1;
            achievements5.RegisterIconIndex(achievementName5, iconIndex5);
            var achievements6 = Main.Achievements;
            var achievementName6 = "HEAVY_METAL";
            var iconIndex6 = num6;
            var num7 = iconIndex6 + 1;
            achievements6.RegisterIconIndex(achievementName6, iconIndex6);
            var achievements7 = Main.Achievements;
            var achievementName7 = "I_AM_LOOT";
            var iconIndex7 = num7;
            var num8 = iconIndex7 + 1;
            achievements7.RegisterIconIndex(achievementName7, iconIndex7);
            var achievements8 = Main.Achievements;
            var achievementName8 = "STAR_POWER";
            var iconIndex8 = num8;
            var num9 = iconIndex8 + 1;
            achievements8.RegisterIconIndex(achievementName8, iconIndex8);
            var achievements9 = Main.Achievements;
            var achievementName9 = "HOLD_ON_TIGHT";
            var iconIndex9 = num9;
            var num10 = iconIndex9 + 1;
            achievements9.RegisterIconIndex(achievementName9, iconIndex9);
            var achievements10 = Main.Achievements;
            var achievementName10 = "EYE_ON_YOU";
            var iconIndex10 = num10;
            var num11 = iconIndex10 + 1;
            achievements10.RegisterIconIndex(achievementName10, iconIndex10);
            var achievements11 = Main.Achievements;
            var achievementName11 = "SMASHING_POPPET";
            var iconIndex11 = num11;
            var num12 = iconIndex11 + 1;
            achievements11.RegisterIconIndex(achievementName11, iconIndex11);
            var achievements12 = Main.Achievements;
            var achievementName12 = "WORM_FODDER";
            var iconIndex12 = num12;
            var num13 = iconIndex12 + 1;
            achievements12.RegisterIconIndex(achievementName12, iconIndex12);
            var achievements13 = Main.Achievements;
            var achievementName13 = "MASTERMIND";
            var iconIndex13 = num13;
            var num14 = iconIndex13 + 1;
            achievements13.RegisterIconIndex(achievementName13, iconIndex13);
            var achievements14 = Main.Achievements;
            var achievementName14 = "WHERES_MY_HONEY";
            var iconIndex14 = num14;
            var num15 = iconIndex14 + 1;
            achievements14.RegisterIconIndex(achievementName14, iconIndex14);
            var achievements15 = Main.Achievements;
            var achievementName15 = "STING_OPERATION";
            var iconIndex15 = num15;
            var num16 = iconIndex15 + 1;
            achievements15.RegisterIconIndex(achievementName15, iconIndex15);
            var achievements16 = Main.Achievements;
            var achievementName16 = "BONED";
            var iconIndex16 = num16;
            var num17 = iconIndex16 + 1;
            achievements16.RegisterIconIndex(achievementName16, iconIndex16);
            var achievements17 = Main.Achievements;
            var achievementName17 = "DUNGEON_HEIST";
            var iconIndex17 = num17;
            var num18 = iconIndex17 + 1;
            achievements17.RegisterIconIndex(achievementName17, iconIndex17);
            var achievements18 = Main.Achievements;
            var achievementName18 = "ITS_GETTING_HOT_IN_HERE";
            var iconIndex18 = num18;
            var num19 = iconIndex18 + 1;
            achievements18.RegisterIconIndex(achievementName18, iconIndex18);
            var achievements19 = Main.Achievements;
            var achievementName19 = "MINER_FOR_FIRE";
            var iconIndex19 = num19;
            var num20 = iconIndex19 + 1;
            achievements19.RegisterIconIndex(achievementName19, iconIndex19);
            var achievements20 = Main.Achievements;
            var achievementName20 = "STILL_HUNGRY";
            var iconIndex20 = num20;
            var num21 = iconIndex20 + 1;
            achievements20.RegisterIconIndex(achievementName20, iconIndex20);
            var achievements21 = Main.Achievements;
            var achievementName21 = "ITS_HARD";
            var iconIndex21 = num21;
            var num22 = iconIndex21 + 1;
            achievements21.RegisterIconIndex(achievementName21, iconIndex21);
            var achievements22 = Main.Achievements;
            var achievementName22 = "BEGONE_EVIL";
            var iconIndex22 = num22;
            var num23 = iconIndex22 + 1;
            achievements22.RegisterIconIndex(achievementName22, iconIndex22);
            var achievements23 = Main.Achievements;
            var achievementName23 = "EXTRA_SHINY";
            var iconIndex23 = num23;
            var num24 = iconIndex23 + 1;
            achievements23.RegisterIconIndex(achievementName23, iconIndex23);
            var achievements24 = Main.Achievements;
            var achievementName24 = "HEAD_IN_THE_CLOUDS";
            var iconIndex24 = num24;
            var num25 = iconIndex24 + 1;
            achievements24.RegisterIconIndex(achievementName24, iconIndex24);
            var achievements25 = Main.Achievements;
            var achievementName25 = "LIKE_A_BOSS";
            var iconIndex25 = num25;
            var num26 = iconIndex25 + 1;
            achievements25.RegisterIconIndex(achievementName25, iconIndex25);
            var achievements26 = Main.Achievements;
            var achievementName26 = "BUCKETS_OF_BOLTS";
            var iconIndex26 = num26;
            var num27 = iconIndex26 + 1;
            achievements26.RegisterIconIndex(achievementName26, iconIndex26);
            var achievements27 = Main.Achievements;
            var achievementName27 = "DRAX_ATTAX";
            var iconIndex27 = num27;
            var num28 = iconIndex27 + 1;
            achievements27.RegisterIconIndex(achievementName27, iconIndex27);
            var achievements28 = Main.Achievements;
            var achievementName28 = "PHOTOSYNTHESIS";
            var iconIndex28 = num28;
            var num29 = iconIndex28 + 1;
            achievements28.RegisterIconIndex(achievementName28, iconIndex28);
            var achievements29 = Main.Achievements;
            var achievementName29 = "GET_A_LIFE";
            var iconIndex29 = num29;
            var num30 = iconIndex29 + 1;
            achievements29.RegisterIconIndex(achievementName29, iconIndex29);
            var achievements30 = Main.Achievements;
            var achievementName30 = "THE_GREAT_SOUTHERN_PLANTKILL";
            var iconIndex30 = num30;
            var num31 = iconIndex30 + 1;
            achievements30.RegisterIconIndex(achievementName30, iconIndex30);
            var achievements31 = Main.Achievements;
            var achievementName31 = "TEMPLE_RAIDER";
            var iconIndex31 = num31;
            var num32 = iconIndex31 + 1;
            achievements31.RegisterIconIndex(achievementName31, iconIndex31);
            var achievements32 = Main.Achievements;
            var achievementName32 = "LIHZAHRDIAN_IDOL";
            var iconIndex32 = num32;
            var num33 = iconIndex32 + 1;
            achievements32.RegisterIconIndex(achievementName32, iconIndex32);
            var achievements33 = Main.Achievements;
            var achievementName33 = "ROBBING_THE_GRAVE";
            var iconIndex33 = num33;
            var num34 = iconIndex33 + 1;
            achievements33.RegisterIconIndex(achievementName33, iconIndex33);
            var achievements34 = Main.Achievements;
            var achievementName34 = "BIG_BOOTY";
            var iconIndex34 = num34;
            var num35 = iconIndex34 + 1;
            achievements34.RegisterIconIndex(achievementName34, iconIndex34);
            var achievements35 = Main.Achievements;
            var achievementName35 = "FISH_OUT_OF_WATER";
            var iconIndex35 = num35;
            var num36 = iconIndex35 + 1;
            achievements35.RegisterIconIndex(achievementName35, iconIndex35);
            var achievements36 = Main.Achievements;
            var achievementName36 = "OBSESSIVE_DEVOTION";
            var iconIndex36 = num36;
            var num37 = iconIndex36 + 1;
            achievements36.RegisterIconIndex(achievementName36, iconIndex36);
            var achievements37 = Main.Achievements;
            var achievementName37 = "STAR_DESTROYER";
            var iconIndex37 = num37;
            var num38 = iconIndex37 + 1;
            achievements37.RegisterIconIndex(achievementName37, iconIndex37);
            var achievements38 = Main.Achievements;
            var achievementName38 = "CHAMPION_OF_TERRARIA";
            var iconIndex38 = num38;
            var num39 = iconIndex38 + 1;
            achievements38.RegisterIconIndex(achievementName38, iconIndex38);
            var achievements39 = Main.Achievements;
            var achievementName39 = "BLOODBATH";
            var iconIndex39 = num39;
            var num40 = iconIndex39 + 1;
            achievements39.RegisterIconIndex(achievementName39, iconIndex39);
            var achievements40 = Main.Achievements;
            var achievementName40 = "GOBLIN_PUNTER";
            var iconIndex40 = num40;
            var num41 = iconIndex40 + 1;
            achievements40.RegisterIconIndex(achievementName40, iconIndex40);
            var achievements41 = Main.Achievements;
            var achievementName41 = "KILL_THE_SUN";
            var iconIndex41 = num41;
            var num42 = iconIndex41 + 1;
            achievements41.RegisterIconIndex(achievementName41, iconIndex41);
            var achievements42 = Main.Achievements;
            var achievementName42 = "WALK_THE_PLANK";
            var iconIndex42 = num42;
            var num43 = iconIndex42 + 1;
            achievements42.RegisterIconIndex(achievementName42, iconIndex42);
            var achievements43 = Main.Achievements;
            var achievementName43 = "DO_YOU_WANT_TO_SLAY_A_SNOWMAN";
            var iconIndex43 = num43;
            var num44 = iconIndex43 + 1;
            achievements43.RegisterIconIndex(achievementName43, iconIndex43);
            var achievements44 = Main.Achievements;
            var achievementName44 = "TIN_FOIL_HATTER";
            var iconIndex44 = num44;
            var num45 = iconIndex44 + 1;
            achievements44.RegisterIconIndex(achievementName44, iconIndex44);
            var achievements45 = Main.Achievements;
            var achievementName45 = "BALEFUL_HARVEST";
            var iconIndex45 = num45;
            var num46 = iconIndex45 + 1;
            achievements45.RegisterIconIndex(achievementName45, iconIndex45);
            var achievements46 = Main.Achievements;
            var achievementName46 = "ICE_SCREAM";
            var iconIndex46 = num46;
            var num47 = iconIndex46 + 1;
            achievements46.RegisterIconIndex(achievementName46, iconIndex46);
            var achievements47 = Main.Achievements;
            var achievementName47 = "SLIPPERY_SHINOBI";
            var iconIndex47 = num47;
            var num48 = iconIndex47 + 1;
            achievements47.RegisterIconIndex(achievementName47, iconIndex47);
            var achievements48 = Main.Achievements;
            var achievementName48 = "STICKY_SITUATION";
            var iconIndex48 = num48;
            var num49 = iconIndex48 + 1;
            achievements48.RegisterIconIndex(achievementName48, iconIndex48);
            var achievements49 = Main.Achievements;
            var achievementName49 = "REAL_ESTATE_AGENT";
            var iconIndex49 = num49;
            var num50 = iconIndex49 + 1;
            achievements49.RegisterIconIndex(achievementName49, iconIndex49);
            var achievements50 = Main.Achievements;
            var achievementName50 = "NOT_THE_BEES";
            var iconIndex50 = num50;
            var num51 = iconIndex50 + 1;
            achievements50.RegisterIconIndex(achievementName50, iconIndex50);
            var achievements51 = Main.Achievements;
            var achievementName51 = "JEEPERS_CREEPERS";
            var iconIndex51 = num51;
            var num52 = iconIndex51 + 1;
            achievements51.RegisterIconIndex(achievementName51, iconIndex51);
            var achievements52 = Main.Achievements;
            var achievementName52 = "FUNKYTOWN";
            var iconIndex52 = num52;
            var num53 = iconIndex52 + 1;
            achievements52.RegisterIconIndex(achievementName52, iconIndex52);
            var achievements53 = Main.Achievements;
            var achievementName53 = "INTO_ORBIT";
            var iconIndex53 = num53;
            var num54 = iconIndex53 + 1;
            achievements53.RegisterIconIndex(achievementName53, iconIndex53);
            var achievements54 = Main.Achievements;
            var achievementName54 = "ROCK_BOTTOM";
            var iconIndex54 = num54;
            var num55 = iconIndex54 + 1;
            achievements54.RegisterIconIndex(achievementName54, iconIndex54);
            var achievements55 = Main.Achievements;
            var achievementName55 = "MECHA_MAYHEM";
            var iconIndex55 = num55;
            var num56 = iconIndex55 + 1;
            achievements55.RegisterIconIndex(achievementName55, iconIndex55);
            var achievements56 = Main.Achievements;
            var achievementName56 = "GELATIN_WORLD_TOUR";
            var iconIndex56 = num56;
            var num57 = iconIndex56 + 1;
            achievements56.RegisterIconIndex(achievementName56, iconIndex56);
            var achievements57 = Main.Achievements;
            var achievementName57 = "FASHION_STATEMENT";
            var iconIndex57 = num57;
            var num58 = iconIndex57 + 1;
            achievements57.RegisterIconIndex(achievementName57, iconIndex57);
            var achievements58 = Main.Achievements;
            var achievementName58 = "VEHICULAR_MANSLAUGHTER";
            var iconIndex58 = num58;
            var num59 = iconIndex58 + 1;
            achievements58.RegisterIconIndex(achievementName58, iconIndex58);
            var achievements59 = Main.Achievements;
            var achievementName59 = "BULLDOZER";
            var iconIndex59 = num59;
            var num60 = iconIndex59 + 1;
            achievements59.RegisterIconIndex(achievementName59, iconIndex59);
            var achievements60 = Main.Achievements;
            var achievementName60 = "THERE_ARE_SOME_WHO_CALL_HIM";
            var iconIndex60 = num60;
            var num61 = iconIndex60 + 1;
            achievements60.RegisterIconIndex(achievementName60, iconIndex60);
            var achievements61 = Main.Achievements;
            var achievementName61 = "DECEIVER_OF_FOOLS";
            var iconIndex61 = num61;
            var num62 = iconIndex61 + 1;
            achievements61.RegisterIconIndex(achievementName61, iconIndex61);
            var achievements62 = Main.Achievements;
            var achievementName62 = "SWORD_OF_THE_HERO";
            var iconIndex62 = num62;
            var num63 = iconIndex62 + 1;
            achievements62.RegisterIconIndex(achievementName62, iconIndex62);
            var achievements63 = Main.Achievements;
            var achievementName63 = "LUCKY_BREAK";
            var iconIndex63 = num63;
            var num64 = iconIndex63 + 1;
            achievements63.RegisterIconIndex(achievementName63, iconIndex63);
            var achievements64 = Main.Achievements;
            var achievementName64 = "THROWING_LINES";
            var iconIndex64 = num64;
            var num65 = iconIndex64 + 1;
            achievements64.RegisterIconIndex(achievementName64, iconIndex64);
            var achievements65 = Main.Achievements;
            var achievementName65 = "DYE_HARD";
            var iconIndex65 = num65;
            var num66 = iconIndex65 + 1;
            achievements65.RegisterIconIndex(achievementName65, iconIndex65);
            var achievements66 = Main.Achievements;
            var achievementName66 = "FREQUENT_FLYER";
            var iconIndex66 = num66;
            var num67 = iconIndex66 + 1;
            achievements66.RegisterIconIndex(achievementName66, iconIndex66);
            var achievements67 = Main.Achievements;
            var achievementName67 = "THE_CAVALRY";
            var iconIndex67 = num67;
            var num68 = iconIndex67 + 1;
            achievements67.RegisterIconIndex(achievementName67, iconIndex67);
            var achievements68 = Main.Achievements;
            var achievementName68 = "COMPLETELY_AWESOME";
            var iconIndex68 = num68;
            var num69 = iconIndex68 + 1;
            achievements68.RegisterIconIndex(achievementName68, iconIndex68);
            var achievements69 = Main.Achievements;
            var achievementName69 = "TIL_DEATH";
            var iconIndex69 = num69;
            var num70 = iconIndex69 + 1;
            achievements69.RegisterIconIndex(achievementName69, iconIndex69);
            var achievements70 = Main.Achievements;
            var achievementName70 = "ARCHAEOLOGIST";
            var iconIndex70 = num70;
            var num71 = iconIndex70 + 1;
            achievements70.RegisterIconIndex(achievementName70, iconIndex70);
            var achievements71 = Main.Achievements;
            var achievementName71 = "PRETTY_IN_PINK";
            var iconIndex71 = num71;
            var num72 = iconIndex71 + 1;
            achievements71.RegisterIconIndex(achievementName71, iconIndex71);
            var achievements72 = Main.Achievements;
            var achievementName72 = "RAINBOWS_AND_UNICORNS";
            var iconIndex72 = num72;
            var num73 = iconIndex72 + 1;
            achievements72.RegisterIconIndex(achievementName72, iconIndex72);
            var achievements73 = Main.Achievements;
            var achievementName73 = "YOU_AND_WHAT_ARMY";
            var iconIndex73 = num73;
            var num74 = iconIndex73 + 1;
            achievements73.RegisterIconIndex(achievementName73, iconIndex73);
            var achievements74 = Main.Achievements;
            var achievementName74 = "PRISMANCER";
            var iconIndex74 = num74;
            var num75 = iconIndex74 + 1;
            achievements74.RegisterIconIndex(achievementName74, iconIndex74);
            var achievements75 = Main.Achievements;
            var achievementName75 = "IT_CAN_TALK";
            var iconIndex75 = num75;
            var num76 = iconIndex75 + 1;
            achievements75.RegisterIconIndex(achievementName75, iconIndex75);
            var achievements76 = Main.Achievements;
            var achievementName76 = "WATCH_YOUR_STEP";
            var iconIndex76 = num76;
            var num77 = iconIndex76 + 1;
            achievements76.RegisterIconIndex(achievementName76, iconIndex76);
            var achievements77 = Main.Achievements;
            var achievementName77 = "MARATHON_MEDALIST";
            var iconIndex77 = num77;
            var num78 = iconIndex77 + 1;
            achievements77.RegisterIconIndex(achievementName77, iconIndex77);
            var achievements78 = Main.Achievements;
            var achievementName78 = "GLORIOUS_GOLDEN_POLE";
            var iconIndex78 = num78;
            var num79 = iconIndex78 + 1;
            achievements78.RegisterIconIndex(achievementName78, iconIndex78);
            var achievements79 = Main.Achievements;
            var achievementName79 = "SERVANT_IN_TRAINING";
            var iconIndex79 = num79;
            var num80 = iconIndex79 + 1;
            achievements79.RegisterIconIndex(achievementName79, iconIndex79);
            var achievements80 = Main.Achievements;
            var achievementName80 = "GOOD_LITTLE_SLAVE";
            var iconIndex80 = num80;
            var num81 = iconIndex80 + 1;
            achievements80.RegisterIconIndex(achievementName80, iconIndex80);
            var achievements81 = Main.Achievements;
            var achievementName81 = "TROUT_MONKEY";
            var iconIndex81 = num81;
            var num82 = iconIndex81 + 1;
            achievements81.RegisterIconIndex(achievementName81, iconIndex81);
            var achievements82 = Main.Achievements;
            var achievementName82 = "FAST_AND_FISHIOUS";
            var iconIndex82 = num82;
            var num83 = iconIndex82 + 1;
            achievements82.RegisterIconIndex(achievementName82, iconIndex82);
            var achievements83 = Main.Achievements;
            var achievementName83 = "SUPREME_HELPER_MINION";
            var iconIndex83 = num83;
            var num84 = iconIndex83 + 1;
            achievements83.RegisterIconIndex(achievementName83, iconIndex83);
            var achievements84 = Main.Achievements;
            var achievementName84 = "TOPPED_OFF";
            var iconIndex84 = num84;
            var num85 = iconIndex84 + 1;
            achievements84.RegisterIconIndex(achievementName84, iconIndex84);
            var achievements85 = Main.Achievements;
            var achievementName85 = "SLAYER_OF_WORLDS";
            var iconIndex85 = num85;
            var num86 = iconIndex85 + 1;
            achievements85.RegisterIconIndex(achievementName85, iconIndex85);
            var achievements86 = Main.Achievements;
            var achievementName86 = "YOU_CAN_DO_IT";
            var iconIndex86 = num86;
            var num87 = iconIndex86 + 1;
            achievements86.RegisterIconIndex(achievementName86, iconIndex86);
            var achievements87 = Main.Achievements;
            var achievementName87 = "SICK_THROW";
            var iconIndex87 = num87;
            var num88 = iconIndex87 + 1;
            achievements87.RegisterIconIndex(achievementName87, iconIndex87);
            var achievements88 = Main.Achievements;
            var achievementName88 = "MATCHING_ATTIRE";
            var iconIndex88 = num88;
            var num89 = iconIndex88 + 1;
            achievements88.RegisterIconIndex(achievementName88, iconIndex88);
            var category1 = AchievementCategory.Slayer;
            Main.Achievements.RegisterAchievementCategory("EYE_ON_YOU", category1);
            Main.Achievements.RegisterAchievementCategory("SLIPPERY_SHINOBI", category1);
            Main.Achievements.RegisterAchievementCategory("WORM_FODDER", category1);
            Main.Achievements.RegisterAchievementCategory("MASTERMIND", category1);
            Main.Achievements.RegisterAchievementCategory("STING_OPERATION", category1);
            Main.Achievements.RegisterAchievementCategory("BONED", category1);
            Main.Achievements.RegisterAchievementCategory("STILL_HUNGRY", category1);
            Main.Achievements.RegisterAchievementCategory("BUCKETS_OF_BOLTS", category1);
            Main.Achievements.RegisterAchievementCategory("THE_GREAT_SOUTHERN_PLANTKILL", category1);
            Main.Achievements.RegisterAchievementCategory("LIHZAHRDIAN_IDOL", category1);
            Main.Achievements.RegisterAchievementCategory("FISH_OUT_OF_WATER", category1);
            Main.Achievements.RegisterAchievementCategory("OBSESSIVE_DEVOTION", category1);
            Main.Achievements.RegisterAchievementCategory("STAR_DESTROYER", category1);
            Main.Achievements.RegisterAchievementCategory("CHAMPION_OF_TERRARIA", category1);
            Main.Achievements.RegisterAchievementCategory("GOBLIN_PUNTER", category1);
            Main.Achievements.RegisterAchievementCategory("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", category1);
            Main.Achievements.RegisterAchievementCategory("WALK_THE_PLANK", category1);
            Main.Achievements.RegisterAchievementCategory("BALEFUL_HARVEST", category1);
            Main.Achievements.RegisterAchievementCategory("ICE_SCREAM", category1);
            Main.Achievements.RegisterAchievementCategory("TIN_FOIL_HATTER", category1);
            Main.Achievements.RegisterAchievementCategory("TIL_DEATH", category1);
            Main.Achievements.RegisterAchievementCategory("THERE_ARE_SOME_WHO_CALL_HIM", category1);
            Main.Achievements.RegisterAchievementCategory("ARCHAEOLOGIST", category1);
            Main.Achievements.RegisterAchievementCategory("PRETTY_IN_PINK", category1);
            Main.Achievements.RegisterAchievementCategory("DECEIVER_OF_FOOLS", category1);
            Main.Achievements.RegisterAchievementCategory("VEHICULAR_MANSLAUGHTER", category1);
            var category2 = AchievementCategory.Explorer;
            Main.Achievements.RegisterAchievementCategory("SMASHING_POPPET", category2);
            Main.Achievements.RegisterAchievementCategory("BEGONE_EVIL", category2);
            Main.Achievements.RegisterAchievementCategory("ITS_HARD", category2);
            Main.Achievements.RegisterAchievementCategory("FUNKYTOWN", category2);
            Main.Achievements.RegisterAchievementCategory("WATCH_YOUR_STEP", category2);
            Main.Achievements.RegisterAchievementCategory("YOU_CAN_DO_IT", category2);
            Main.Achievements.RegisterAchievementCategory("BLOODBATH", category2);
            Main.Achievements.RegisterAchievementCategory("KILL_THE_SUN", category2);
            Main.Achievements.RegisterAchievementCategory("STICKY_SITUATION", category2);
            Main.Achievements.RegisterAchievementCategory("NO_HOBO", category2);
            Main.Achievements.RegisterAchievementCategory("IT_CAN_TALK", category2);
            Main.Achievements.RegisterAchievementCategory("HEART_BREAKER", category2);
            Main.Achievements.RegisterAchievementCategory("I_AM_LOOT", category2);
            Main.Achievements.RegisterAchievementCategory("ROBBING_THE_GRAVE", category2);
            Main.Achievements.RegisterAchievementCategory("GET_A_LIFE", category2);
            Main.Achievements.RegisterAchievementCategory("JEEPERS_CREEPERS", category2);
            Main.Achievements.RegisterAchievementCategory("WHERES_MY_HONEY", category2);
            Main.Achievements.RegisterAchievementCategory("DUNGEON_HEIST", category2);
            Main.Achievements.RegisterAchievementCategory("BIG_BOOTY", category2);
            Main.Achievements.RegisterAchievementCategory("ITS_GETTING_HOT_IN_HERE", category2);
            Main.Achievements.RegisterAchievementCategory("INTO_ORBIT", category2);
            Main.Achievements.RegisterAchievementCategory("ROCK_BOTTOM", category2);
            Main.Achievements.RegisterAchievementCategory("OOO_SHINY", category2);
            Main.Achievements.RegisterAchievementCategory("EXTRA_SHINY", category2);
            Main.Achievements.RegisterAchievementCategory("PHOTOSYNTHESIS", category2);
            var category3 = AchievementCategory.Challenger;
            Main.Achievements.RegisterAchievementCategory("GELATIN_WORLD_TOUR", category3);
            Main.Achievements.RegisterAchievementCategory("SLAYER_OF_WORLDS", category3);
            Main.Achievements.RegisterAchievementCategory("REAL_ESTATE_AGENT", category3);
            Main.Achievements.RegisterAchievementCategory("YOU_AND_WHAT_ARMY", category3);
            Main.Achievements.RegisterAchievementCategory("TOPPED_OFF", category3);
            Main.Achievements.RegisterAchievementCategory("MECHA_MAYHEM", category3);
            Main.Achievements.RegisterAchievementCategory("BULLDOZER", category3);
            Main.Achievements.RegisterAchievementCategory("NOT_THE_BEES", category3);
            Main.Achievements.RegisterAchievementCategory("RAINBOWS_AND_UNICORNS", category3);
            Main.Achievements.RegisterAchievementCategory("THROWING_LINES", category3);
            Main.Achievements.RegisterAchievementCategory("FREQUENT_FLYER", category3);
            Main.Achievements.RegisterAchievementCategory("LUCKY_BREAK", category3);
            Main.Achievements.RegisterAchievementCategory("MARATHON_MEDALIST", category3);
            Main.Achievements.RegisterAchievementCategory("SERVANT_IN_TRAINING", category3);
            Main.Achievements.RegisterAchievementCategory("GOOD_LITTLE_SLAVE", category3);
            Main.Achievements.RegisterAchievementCategory("TROUT_MONKEY", category3);
            Main.Achievements.RegisterAchievementCategory("FAST_AND_FISHIOUS", category3);
            Main.Achievements.RegisterAchievementCategory("SUPREME_HELPER_MINION", category3);
            var category4 = AchievementCategory.Collector;
            Main.Achievements.RegisterAchievementCategory("OBTAIN_HAMMER", category4);
            Main.Achievements.RegisterAchievementCategory("HEAVY_METAL", category4);
            Main.Achievements.RegisterAchievementCategory("STAR_POWER", category4);
            Main.Achievements.RegisterAchievementCategory("MINER_FOR_FIRE", category4);
            Main.Achievements.RegisterAchievementCategory("HEAD_IN_THE_CLOUDS", category4);
            Main.Achievements.RegisterAchievementCategory("DRAX_ATTAX", category4);
            Main.Achievements.RegisterAchievementCategory("PRISMANCER", category4);
            Main.Achievements.RegisterAchievementCategory("SWORD_OF_THE_HERO", category4);
            Main.Achievements.RegisterAchievementCategory("HOLD_ON_TIGHT", category4);
            Main.Achievements.RegisterAchievementCategory("THE_CAVALRY", category4);
            Main.Achievements.RegisterAchievementCategory("DYE_HARD", category4);
            Main.Achievements.RegisterAchievementCategory("MATCHING_ATTIRE", category4);
            Main.Achievements.RegisterAchievementCategory("FASHION_STATEMENT", category4);
            Main.Achievements.RegisterAchievementCategory("COMPLETELY_AWESOME", category4);
            Main.Achievements.RegisterAchievementCategory("TIMBER", category4);
            Main.Achievements.RegisterAchievementCategory("SICK_THROW", category4);
            Main.Achievements.RegisterAchievementCategory("GLORIOUS_GOLDEN_POLE", category4);
            Main.Achievements.RegisterAchievementCategory("TEMPLE_RAIDER", category4);
            Main.Achievements.RegisterAchievementCategory("LIKE_A_BOSS", category4);
            Main.Achievements.Load();
            Main.Achievements.OnAchievementCompleted +=
                new Achievement.AchievementCompleted(AchievementInitializer.OnAchievementCompleted);
            AchievementsHelper.Initialize();
        }

        private static void OnAchievementCompleted(Achievement achievement)
        {
            Main.NewText(
                Language.GetTextValue("Achievements.Completed",
                    (object) AchievementTagHandler.GenerateTag(achievement)), byte.MaxValue, byte.MaxValue,
                byte.MaxValue, false);
        }
    }
}